<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800">Rekap Absensi PKL</h2></x-slot>
    <div class="py-8"><div class="max-w-7xl mx-auto sm:px-6 lg:px-8 bg-white border border-gray-100 shadow-sm rounded-2xl overflow-hidden">
        <form class="p-6 grid gap-3 md:grid-cols-4"><input type="date" name="tanggal" value="{{ request('tanggal') }}" class="rounded-xl border-gray-200"><select name="rombel_id" class="rounded-xl border-gray-200"><option value="">Semua rombel</option>@foreach($rombels as $r)<option value="{{ $r->id }}" @selected(request('rombel_id')==$r->id)>{{ $r->nama_rombel }}</option>@endforeach</select><input name="search" value="{{ request('search') }}" class="rounded-xl border-gray-200" placeholder="Cari siswa/NIS"><button class="rounded-xl border px-4">Filter</button></form>
        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-100"><thead class="bg-gray-50"><tr><th class="px-6 py-3 text-left text-xs font-bold text-gray-500">Siswa</th><th class="px-6 py-3 text-left text-xs font-bold text-gray-500">Rombel/Industri</th><th class="px-6 py-3 text-left text-xs font-bold text-gray-500">Check In</th><th class="px-6 py-3 text-left text-xs font-bold text-gray-500">Check Out</th><th class="px-6 py-3 text-left text-xs font-bold text-gray-500">Lokasi</th></tr></thead><tbody class="divide-y divide-gray-100">
            @forelse($absensis as $a)<tr><td class="px-6 py-4"><p class="font-semibold">{{ $a->penempatan?->siswa?->nama_lengkap }}</p><p class="text-xs text-gray-500">{{ $a->tanggal?->format('d M Y') }}</p></td><td class="px-6 py-4 text-sm">{{ $a->penempatan?->rombelPkl?->nama_rombel }}<br><span class="text-gray-500">{{ $a->penempatan?->rombelPkl?->industri?->nama_industri }}</span></td><td class="px-6 py-4">{{ $a->check_in_at ?? '-' }}</td><td class="px-6 py-4">{{ $a->check_out_at ?? '-' }}</td><td class="px-6 py-4 text-xs">@if($a->check_in_latitude)<a class="text-blue-600" target="_blank" href="https://www.openstreetmap.org/?mlat={{ $a->check_in_latitude }}&mlon={{ $a->check_in_longitude }}#map=18/{{ $a->check_in_latitude }}/{{ $a->check_in_longitude }}">Lihat OSM</a>@else - @endif</td></tr>@empty<tr><td colspan="5" class="px-6 py-10 text-center text-gray-500">Belum ada data absensi.</td></tr>@endforelse
        </tbody></table></div><div class="p-6">{{ $absensis->links() }}</div>
    </div></div>
</x-app-layout>
